### ISSUE TITLE
Add autocomplete for Teacher and Subject

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#15] opened 2021-06-03 06:45 UTC
Currently the user can enter freely the Teacher name and Subject in the step below in the Schools accreditation survey. A predefined list shall be first extracted when the app is setup (same as loading Schools from API as described in https://github.com/ghachey/pacific-emis-education-survey-tool/issues/13). From this list the fields shall now be an autocomplete. After typing for example 3 characters a short list of choices matching the characters will be display to user for selection. Typing additional characters will shorten then list dynamically. If the Teacher is not in the list the field can accept the fully typed name also. This will improve data quality by linking with known data in the system.

When recording this in the XML of the survey currently is sets teacherName as shown below. This is good, but when retrieving from the EMIS we will also get the ability to put the teacher ID there. So this can only be added if users selected a teacher from list. But if so, add below teacherName tID=IDOFTEACHER.

The same shall be done for subjects (which can also have an ID called subjCode if selected from list).

![autocomplete](https://user-images.githubusercontent.com/1091769/120597262-6c2d6a00-c477-11eb-8029-2f47644669a2.png)

And these UI widgets shall be available in any other surveys in the tablet. Currently there is only one other example in WASH.

![autocomplete-2](https://user-images.githubusercontent.com/1091769/120597402-9121dd00-c477-11eb-8df4-a71d1395a48e.png)

The REST API call to get the data will be added here soon.

**Comment by ZXeRRinor** [comment] 2021-06-07 14:27
Created and completed task NDOE-230 for this issue.

**Comment by ghachey** [comment] 2021-09-08 03:11
Question from Omega-R:

1. How to get subjects for FedEMIS?
We are getting an empty list when requesting Core Data Collection, and the request /api/subjects returns an empty list too. 
A similar request to MIEMIS works fine http://pacifici-emis-address/api/subjects.

2. A token is required for getting a list of Teachers from the EMIS API. We need a user login and password to generate a token. Which one should we use - user login and password or do we need one hardcoded into the app?

**Comment by ghachey** [comment] 2021-09-08 03:14
To which I replied:

The user credentials should be configurable from the Firebase projects. For example, for FedEMIS you would publish the additional settings like below screenshot. You will need one for each context/ountry (e.g. MIEMIS Education Survey Tool will need the same for MIEMIS.)

For the time being, you can use the user you are using for the Pacific Open Education Data app (user details sent to your email). But these users will be refined and will change.

And we will do the same for the Pacific Open Education Data app (I added the comment in the related issue https://github.com/ghachey/pacific-open-education-data/issues/4).

**Comment by ghachey** [comment] 2021-10-30 06:40
While your suggestions are better yes, I do not believe this is the case. Because I tried with force get schools, teachers and subjects and it returns that same error. The FedEMIS server is running and my Internet connection is strong. We have schools (its the most basic data and has been there for many years). We have teachers and we have subjects. I think you need to look into this a bit more deeply/

**Comment by marinaomega** [comment] 2021-11-01 11:54
Sure, we'll double-check that!

**Comment by ghachey** [comment] 2021-11-04 03:28
This problem still exists as of version 02.11.21

**Comment by marinaomega** [comment] 2021-11-08 12:05
Yes, we are on it

**Comment by marinaomega** [comment] 2021-11-10 12:11
At the moment we are working on the fix. The issue is reproduced when user updates the version from an old one (released in June or before) to the newest. It can be solved for now by updating either RemoteSettings (Force fetch remote settings button) or context. Issue is not reproduced if it's the first app launch.

**Comment by ghachey** [comment] 2021-11-12 03:03
I believe this is due to the device not recognizing the SSL certificate of the server. The SSL certificate is valid and recognized by all major browsers updated to the latest on Windows 10 and MacOS. It is not a problem on some of our device but older devices it is. Please refer to my email on this for my proposed solution in the interim.

**Comment by ghachey** [comment] 2021-11-17 02:16
This can be considered fixed

**Closed** 2021-11-17 02:17 UTC
Labels: enhancement
